version: '3.8'

services:
  academy-cart:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0 --port=8000'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - cart
    networks:
      - app-net

  cart:
    image: mysql:8.0.37
    container_name: mysql
    environment:
      MYSQL_PASSWORD: "taipro573@"
      MYSQL_ROOT_PASSWORD: "taipro573@"
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-net

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work --queue=emails'
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - cart
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql:
